fix exit code

diff --git a/.github/workflows/app-deployment-template.yml b/.github/workflows/app-deployment-template.yml
--- a/.github/workflows/app-deployment-template.yml
+++ b/.github/workflows/app-deployment-template.yml
@@ -150,9 +150,13 @@ jobs:
           export RELEASE_NAME=$(helmfile -e ${ENV_NAME} list --output json | jq -r '.[].name')
           export IMAGE_TAG=$(helm get values ${RELEASE_NAME} -n ${NAMESPACE} --output  json | jq -r '.deployment.image.tag')
 
-          # Run diff first with detailed exit code
+          # Temporarily disable error handling
+          set +e
           helmfile diff -e ${ENV_NAME} --set deployment.image.tag=${IMAGE_TAG} --detailed-exitcode
           DIFF_EXIT_CODE=$?
+
+          # Re-enable error handling
+          set -eo pipefail
 
           if [ "$DIFF_EXIT_CODE" == "0" ]; then
             echo "No changes detected, skipping sync"
@@ -160,6 +164,6 @@ jobs:
             echo "Changes detected, applying updates..."
             helmfile sync -e ${ENV_NAME} --set deployment.image.tag=${IMAGE_TAG}
           else
-            echo "Error running helmfile diff"
+            echo "Error running helmfile diff with exit code: $DIFF_EXIT_CODE"
             exit 1
           fi
